scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 60s
    scheme: http

    static_configs:
      - targets: [
        'back:5051',
      ]
        labels:
          service: 'app-exporter'
          group: 'testing'
          name: 'app-exporter'
